In [3]:
!pip install joblib

In [4]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import joblib

In [23]:
class perceptron:
    def __init__(self,eta: float = None,epochs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        #training of the perceptron
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    #prediction of the perceptron        
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
            

In [9]:
obj = perceptron(eta = 0.01,epochs=10)

In [27]:
z = 0
np.where(z > 0, 1, 0)

array(0)

In [11]:
obj.epochs

10

In [12]:
obj.weights


array([2.56454252e-05, 3.89351841e-05, 2.02127555e-04])

In [15]:
OR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,1]
}

df_or = pd.DataFrame(OR)

In [28]:
x_OR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,0]
}
df_xor = pd.DataFrame(x_OR)

In [29]:
df_xor

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [32]:
X, y = prepare_data(df_xor)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [16]:
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [33]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [31]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [20]:
X, y = prepare_data(df_or)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [38]:
#training the model
X, y = prepare_data(df_xor)

ETA = 0.1
EPOCHS = 10

model_xor = perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 1 0]
error: 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 4.81540266e-05  9.98992953e-02 -9.99927695e-02]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[-0.09995185 -0.0001007   0.10000723]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 4.81540266e-05  9.98992953e-02 -9.99927695e-02]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2   

The updated weight gave me correct value after 6th epoch

#similarly for AND gate

In [35]:
And = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}
df_and = pd.DataFrame(And)

In [36]:
X, y = prepare_data(df_and)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [37]:
X, y = prepare_data(df_xor)

ETA = 0.1
EPOCHS = 10

model_and = perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10005735  0.0999589  -0.19992822]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 5.73505454e-05 -4.11017646e-05  7.17827144e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.10005735  0.0999589  -0.19992822]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Na